meta_product_name: "PxlSounds"
meta_title: "PxlSounds - Explore"
meta_description: "An app where you can create your own environment"
meta_image: "card.png" # should exist in `app/assets/images/`
twitter_account: ""   # required for Twitter Cards
